export type AnalyticsTransactionNames =
  | "Wrap"
  | "Unwrap"
  | "Approve Allowance"
  | "Send Stream"
  | "Send Transfer"
  | "Modify Stream"
  | "Cancel Stream"
  | "Approve IDA Subscription"
  | "Revoke IDA Subscription"
  | "Create Vesting Schedule"
  | "Delete Vesting Schedule"
  | "Claim Vesting Schedule"
  | "Fix Access for Vesting"
  | "Approve Auto-Wrap Allowance"
  | "Enable Auto-Wrap"
  | "Revoked Permissions & Allowances"
  | "Updated Permissions & Allowances"
  | "Disable Auto-Wrap"
  | "Connect to GDA Pool"
  | "Disconnect from GDA Pool";
